"""Remove url foreign key

Revision ID: 157764184261
Revises: 860cc9f942ef
Create Date: 2025-02-01 20:27:42.630988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157764184261'
down_revision: Union[str, None] = '860cc9f942ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('embeddings_github_url_fkey', 'embeddings', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('embeddings_github_url_fkey', 'embeddings', 'chats', ['github_url'], ['github_url'])
    # ### end Alembic commands ###
