"""On delete cascade

Revision ID: 179144f7bba8
Revises: 157764184261
Create Date: 2025-02-01 21:12:11.256004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179144f7bba8'
down_revision: Union[str, None] = '157764184261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_chat_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chats_user_id_fkey', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('chats_user_id_fkey', 'chats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_chat_id_fkey', 'chat_messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
