"""Changed file tree to repo info

Revision ID: 66105121c6a1
Revises: 7b264eed2a3d
Create Date: 2025-01-31 00:06:42.419284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66105121c6a1'
down_revision: Union[str, None] = '7b264eed2a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('repo_info', sa.String(), nullable=True))
    op.drop_column('chats', 'file_tree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('file_tree', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'repo_info')
    # ### end Alembic commands ###
