"""Revise repos table to chats

Revision ID: 788057e6e1c7
Revises: b9b21f23fd29
Create Date: 2025-01-21 17:01:37.471622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788057e6e1c7'
down_revision: Union[str, None] = 'b9b21f23fd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_github_url'), 'chats', ['github_url'], unique=True)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.drop_index('ix_repos_github_url', table_name='repos')
    op.drop_index('ix_repos_id', table_name='repos')
    op.drop_table('repos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='repos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='repos_pkey')
    )
    op.create_index('ix_repos_id', 'repos', ['id'], unique=False)
    op.create_index('ix_repos_github_url', 'repos', ['github_url'], unique=True)
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_github_url'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
