"""Added fields for progress bar

Revision ID: 7b264eed2a3d
Revises: a8d37e161626
Create Date: 2025-01-27 00:37:03.781720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b264eed2a3d'
down_revision: Union[str, None] = 'a8d37e161626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message', sa.String(), nullable=True))
    op.drop_column('chat_messages', 'content')
    op.add_column('chats', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('indexed_chunks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'indexed_chunks')
    op.drop_column('chats', 'total_chunks')
    op.add_column('chat_messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chat_messages', 'message')
    # ### end Alembic commands ###
