"""Add is_bookmarked

Revision ID: 860cc9f942ef
Revises: 66105121c6a1
Create Date: 2025-01-31 05:12:20.911950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860cc9f942ef'
down_revision: Union[str, None] = '66105121c6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_bookmarked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_bookmarked')
    # ### end Alembic commands ###
