"""Move to pinecone

Revision ID: 9e0409c3aced
Revises: 7d10d40621e2
Create Date: 2025-02-04 19:44:13.174134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e0409c3aced'
down_revision: Union[str, None] = '7d10d40621e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_github_url', table_name='embeddings')
    op.drop_index('ix_embeddings_id', table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('chunks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    op.create_index('ix_embeddings_id', 'embeddings', ['id'], unique=False)
    op.create_index('ix_embeddings_github_url', 'embeddings', ['github_url'], unique=False)
    # ### end Alembic commands ###
