"""Revision to embeddings table

Revision ID: a8d37e161626
Revises: aa875175dcc9
Create Date: 2025-01-26 22:47:51.301533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d37e161626'
down_revision: Union[str, None] = 'aa875175dcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('chunks', sa.JSON(), nullable=True))
    op.drop_column('embeddings', 'chunk_metadata')
    op.drop_column('embeddings', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('embeddings', sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('embeddings', 'chunks')
    # ### end Alembic commands ###
